contents:
  repositories:
    - https://packages.cgr.dev/extras
  keyring:
    - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
  packages:
    - apk-tools
    - apko
    - bash
    - bash-binsh
    - bash-completion
    - bubblewrap
    - build-base
    - busybox
    - byobu
    - ca-certificates-bundle
    - chainctl
    - containerd-service
    - coreutils
    - crane
    - curl
    - dbus
    - docker
    - docker-cli
    - docker-compose
    - docker-credential-gcr
    - docker-dind
    - dockerd
    - dockerd-service
    - e2fsprogs
    - emacs
    - gh
    - git
    - git-completion
    - gitsign
    - gitsign-config
    - gitsign-credential-cache
    - go
    # - goimports
    - google-cloud-sdk
    - grype
    - helm
    - iproute2
    - jq
    - k3d
    - kind
    - kmod
    - kmod-libs
    - kubectl-latest
    - less
    - malcontent
    - man-db
    - melange
    - mount
    - neovim
    - opendoas
    - opentofu
    - screen
    - spdx-tools-java
    - ssh-import-id
    - sudo-rs
    - terraform
    - terraform-docs
    - tree
    - udev
    - umount
    - util-linux-misc
    - vim
    - vscode-skip-server-requirements-check
    - wolfi-baselayout
    - wolfictl
    - yam
    - yq
    - zsh

environment:
  COLORTERM: truecolor
  TERM: xterm-256color

entrypoint:
  command: /usr/bin/sdk

volumes:
  - "/var/lib/docker"
